### ISSUE TITLE
Search results have `indexundefined` appended in URL, resulting in 404s

### ISSUE THREAD

**Issue by CBroz1** [datajoint/datajoint-tutorial#26]
Search anything in the searchbar on tutorials.datajoint.io - [example link](https://tutorials.datajoint.io/search.html?q=installing+datajoint+for+python&check_keywords=yes&area=default#) - returns a list with `indexundefined` in the URLs. 

```
404 Not Found
Code: NoSuchKey
Message: The specified key does not exist.
Key: setting-up/datajoint-pythonundefined
RequestId: 66RGTWTHG3EX9QFY
HostId: W0DRWvIYiXBYRVkM+nbSt1YVSHpDzaSHznJECmBUTyhCSNe+UWcEdGxO5LhqnhH7GMFCEsrE8WU=
```

**Comment by guzman-raphael** [comment]
@CBroz1 Thanks for the report. I think you may have stumbled across an old [issue](https://github.com/datajoint/datajoint-tutorial/issues/13)... :sweat_smile: Let me see if we can find some time to address this soon.

**Comment by CBroz1** [comment]
Closing duplicate

**Comment by zitrosolrac** [comment]
We found that after you click on a search result (ex: search for schema and this would be one of the links https://tutorials.datajoint.io/beginner/building-first-pipeline/python/first-table**undefined**?highlight=schema) we need to substitute **undefined** with **.html**. This is a work around while we find a fix.
