### ISSUE TITLE
Instruct users to build a pipeline with .py files.

### ISSUE THREAD

**Issue by shenshan** [datajoint/datajoint-tutorial#6]
In the "building your first pipeline"-"building in python" section (https://tutorials.datajoint.io/beginner/building-first-pipeline/python/first-table.html), there is only an example if everything is in the interactive python console. I think we also need to instruct the user how to put them into a .py file.

**Comment by eywalker** [comment]
Putting the pipeline code into a separate `.py` file is covered in https://tutorials.datajoint.io/beginner/building-first-pipeline/python/save-tables.html#defining-your-table-module

**Comment by shenshan** [comment]
Thanks. Just saw it.
